force-app/main/default/objects/Account/fields/ContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactLastName__c.field-meta.xml
<CustomField>
    <fullName>ContactLastName__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
public with sharing class AccountTriggerHelper {

    public static void createRelatedContacts(List<Account> accounts) {
        List<Contact> contacts = new List<Contact>();

        for (Account acc : accounts) {
            contacts.add(createContactFromAccount(acc));
        }

        insert contacts;
    }

    private static Contact createContactFromAccount(Account acc) {
        return new Contact(
            FirstName = acc.ContactFirstName__c,
            LastName = acc.ContactLastName__c,
            Email = acc.Email__c,
            Phone = acc.ContactPhone__c
        );
    }

}