force-app/main/default/objects/Account/fields/ContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactLastName__c.field-meta.xml
<CustomField>
    <fullName>ContactLastName__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountSelectors.cls
public with sharing class AccountSelectors {

    public static List<Account> getAccountsWithContacts(List<Account> accounts) {
        return [
            SELECT
                (SELECT Id FROM Contacts),
                ContactFirstName__c,
                ContactLastName__c,
                ContactPhone__c,
                Email__c
            FROM Account
            WHERE Id IN :accounts
        ];
    }

    public static List<Account> getByExternalId(String externalId) {
        return [SELECT Id FROM Account WHERE ExternalId__c = :externalId];
    }

}