force-app/main/default/objects/Account/fields/ContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactLastName__c.field-meta.xml
<CustomField>
    <fullName>ContactLastName__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/TestBuilders.cls
@isTest
public with sharing class TestBuilders {

    private static final String DEFAULT_ACCOUNT_NAME = 'Test Account';

    private static Integer accountCount = 0;

    public static AccountBuilder accountBuilder() {
        return new AccountBuilder();
    }

    public class AccountBuilder {

        private Account record;

        public AccountBuilder() {
            this.record = new Account(
                Name = DEFAULT_ACCOUNT_NAME + ++accountCount
            );
        }

        public AccountBuilder setName(String name) {
            this.record.Name = name;
            return this;
        }

        public AccountBuilder setEmail(String email) {
            this.record.Email__c = email;
            return this;
        }

        public AccountBuilder setContactFirstName(String contactFirstName) {
            this.record.ContactFirstName__c = contactFirstName;
            return this;
        }

        public AccountBuilder setContactLastName(String contactLastName) {
            this.record.ContactLastName__c = contactLastName;
            return this;
        }

        public AccountBuilder setContactPhone(String phone) {
            this.record.ContactPhone__c = phone;
            return this;
        }

        public Account get() {
            return this.record;
        }

        public Account insertAndGet() {
            insert this.record;
            return this.record;
        }
    }

}